version = 1

[[annotations]]
path = [
    ".clang-format",
    ".vscode/settings.json",
    ".devcontainer/devcontainer.json",
    ".pre-commit-config.yaml"


]
SPDX-FileCopyrightText = "2025 Aaron White <w531t4@gmail.com>"
SPDX-License-Identifier = "MIT"
